# Generated by Django 2.2.3 on 2019-07-15 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacioliApp', '0003_auto_20190712_1015'),
    ]

    operations = [
        migrations.CreateModel(
            name='PgDiariolibro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ccod_cue', models.CharField(blank=True, max_length=50, null=True)),
                ('ndebe', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('nhaber', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('cglosa', models.CharField(blank=True, max_length=250, null=True)),
                ('ccod_ori', models.CharField(blank=True, max_length=250, null=True)),
                ('nasiento', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
            ],
            options={
                'db_table': 'pg_diariolibro',
                'managed': False,
            },
        ),
    ]
